###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './xdebug.ini:/etc/php/conf.d/xdebug.ini'
        environment:
            - XDEBUG_SESSION=docker-server
        ports:
            - '48000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    mysql:
        image: 'biarms/mysql'
        working_dir: /application
        volumes:
            - './application:/application'
            - './mysql_data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=to_do_list
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - '23002:3306'

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '5001:80'
        depends_on:
            - 'mysql'

volumes:
    mysql_data: